CREATE TABLE if not exists tb_wallet_record (
 `id` bigint(20) NOT NULL AUTO_INCREMENT,
 `order_id` bigint(20) DEFAULT NULL COMMENT '订单id',
 `order_code` varchar(64) DEFAULT NULL COMMENT '订单编码',
 `company_id` varchar(32) DEFAULT NULL,
 `wallet_id` bigint(20) DEFAULT NULL COMMENT '钱包id',
 `wallet_code` varchar(64) DEFAULT NULL COMMENT '钱包编码',
 `cuser_id` varchar(64) DEFAULT NULL COMMENT '用户id',
 `cuser_name` varchar(16) DEFAULT NULL COMMENT '用户名称',
 `cuser_telephone` varchar(20) DEFAULT NULL COMMENT '用户电话',
 `cuser_sex` varchar(3) DEFAULT NULL COMMENT '用户性别',
 `record_type` int(3) DEFAULT NULL COMMENT '流水记录类型（1：充值、2：消费、3：退款）',
 `amount` bigint(20) DEFAULT NULL COMMENT '消费金额，单位分',
 `balance` bigint(20) DEFAULT NULL COMMENT '账户余额',
 `title` varchar(32) DEFAULT NULL COMMENT '流水标题',
 `content` varchar(255) DEFAULT NULL COMMENT '流水内容',
 `trade_type` varchar(64) DEFAULT NULL COMMENT '支付方式',
 `trade_no` varchar(64) DEFAULT NULL COMMENT '中台支付订单号',
 `trade_time` bigint(20) DEFAULT NULL COMMENT '交易时间',
 `medium_id` bigint(20) DEFAULT NULL COMMENT '交易渠道（POS，官网，APP）',
 `medium_type` varchar(16) DEFAULT NULL COMMENT '交易渠道（POS，官网，APP）',
 `medium_code` varchar(64) DEFAULT NULL,
 `status` int(3) DEFAULT NULL COMMENT '状态（0：正常、1：异常）',
 `channel_type` varchar(16) COMMENT '支付渠道类型',
 `create_time` bigint(20) DEFAULT NULL,
 PRIMARY KEY (`id`),
 KEY `order_id_INDEX` (`order_id`),
 KEY `order_code_INDEX` (`order_code`),
 KEY `company_id_INDEX` (`company_id`),
 KEY `wallet_code_INDEX` (`wallet_code`),
 KEY `create_time_INDEX` (`create_time`)
) ENGINE=InnoDB;